"""
FinOps data-ingestion visibility.

Answers the two questions that otherwise leave a fresh deployment flying blind:

  1. "What is actually IN the database right now?" — per table: row count, date
     coverage, freshness, and a per-subscription breakdown, so an empty chart can be
     traced to an empty table rather than guessed at.
  2. "Is a collection running, and what has it written so far?" — the force-ingest job
     in main.py records its progress here.

The dataset catalogue itself lives in data_availability_service.DATASETS; this module
adds the per-subscription and size detail the FinOps ingestion tab needs, and owns the
shared job state so both the API and the collectors can see the same run.
"""
from __future__ import annotations

import logging
import threading
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from services.database import get_connection, is_azure_sql
from services import data_availability_service as _av

logger = logging.getLogger(__name__)

# Only tables declared in the catalogue may be interpolated into SQL below.
_ALLOWED_TABLES = {m["table"] for m in _av.DATASETS.values()}

# Candidate column names carrying the owning subscription, most specific first.
_SUB_COLUMNS = ("subscription_id", "subscriptionid", "sub_id")

# How a dataset gets filled. "Empty" means very different things across these three,
# and without saying so the UI leaves the user hunting a pipeline fault that is really
# just a table waiting on a precondition.
#   collection  — a Collect run pulls it from Azure
#   derived     — computed from other data once a condition is met; cannot be pulled
#   user_action — only the customer can supply it
FILL_METHOD: Dict[str, Dict[str, str]] = {
    # Pulled from Azure by a collection run.
    "finops_daily_dimension_costs": {"method": "collection", "how": "Filled by the cost warehouse ETL step."},
    "finops_daily_resource_costs": {"method": "collection", "how": "Filled by the cost warehouse ETL step. Azure rate-limits per-resource cost, so coverage is partial by design."},
    "finops_daily_subscription_costs": {"method": "collection", "how": "Filled by the cost warehouse ETL step."},
    "finops_monthly_service_costs": {"method": "collection", "how": "Filled by the cost warehouse ETL step."},
    "finops_monthly_tag_costs": {"method": "collection", "how": "Filled by the ETL, but only for resources that actually carry tags. Tag the estate to populate it."},
    "finops_daily_meter_costs": {"method": "collection", "how": "Filled by the cost warehouse ETL step."},
    "finops_resource_utilization": {"method": "collection", "how": "Filled by the utilisation metrics step."},
    "finops_storage_capacity": {"method": "collection", "how": "Filled by the utilisation metrics step."},
    "finops_la_table_costs": {"method": "collection", "how": "Filled by the Log Analytics step. Needs a readable workspace in scope."},
    "finops_mgmt_group_costs": {"method": "collection", "how": "Filled by the ETL. Requires Management Group Reader on the tenant root."},
    "finops_budgets": {"method": "collection", "how": "Synced from Azure Budgets by the ETL."},
    "finops_recommendations": {"method": "collection", "how": "Generated by the recommendations step from warehouse facts."},
    "scans": {"method": "collection", "how": "Written by the estate scan step."},
    "resource_metrics": {"method": "collection", "how": "Written by the estate scan and utilisation steps."},
    "security_findings": {"method": "collection", "how": "Written by the estate scan step."},

    # Derived — a collection run alone will not create rows.
    "finops_anomalies": {"method": "derived", "how": "Appears only when a resource above $5/day spikes >50% over its 7-day average. Nothing to download."},
    "finops_savings_ledger": {"method": "derived", "how": "Fills only after a recommendation is marked Implemented, then measured. Nothing to download."},
    "resource_snapshots": {"method": "derived", "how": "Needs at least two estate scans to diff. Run a second collection later."},
    "ai_analyses": {"method": "derived", "how": "Written when an AI panel is run. Not part of a collection."},

    # Only the customer can supply these.
    "resource_bcdr_metadata": {"method": "user_action", "how": "Entered in BCDR Planning — criticality, RTO and RPO per resource."},
    "resource_custom_tags": {"method": "user_action", "how": "Added in the Tags module."},
    "projects": {"method": "user_action", "how": "Created in the Projects module."},
    "assessments": {"method": "user_action", "how": "Created by saving an assessment."},
    "onprem_servers": {"method": "user_action", "how": "Uploaded or discovered in the On-Premises module."},
}

_FILL_FALLBACK = {"method": "collection", "how": "Filled by a collection run."}


# ── Shared job state ─────────────────────────────────────────────────────────
# One force-ingest run at a time. Guarded by a lock because the collectors run in a
# thread pool while the API reads this from the event loop.
_JOB_LOCK = threading.Lock()
_JOB: Dict[str, Any] = {
    "running": False,
    "run_id": None,
    "started_at": None,
    "finished_at": None,
    "triggered_by": None,
    "current_step": None,
    "status": "idle",          # idle | running | completed | partial | failed
    "steps": [],               # [{key,label,status,started_at,finished_at,detail,rows}]
    "rows_before": {},
    "rows_after": {},
    "error": None,
}


def job_snapshot() -> Dict[str, Any]:
    """Thread-safe copy of the current/last run for the status endpoint."""
    with _JOB_LOCK:
        snap = {k: (v.copy() if isinstance(v, (dict, list)) else v) for k, v in _JOB.items()}
        snap["steps"] = [dict(s) for s in _JOB["steps"]]
    if snap.get("started_at") and not snap.get("finished_at"):
        try:
            started = datetime.fromisoformat(snap["started_at"])
            snap["elapsed_seconds"] = round((datetime.now(timezone.utc) - started).total_seconds(), 1)
        except Exception:
            pass
    # Net rows written so far, per table — the number the user actually cares about.
    before, after = snap.get("rows_before") or {}, snap.get("rows_after") or {}
    if before and after:
        delta = {t: after.get(t, 0) - before.get(t, 0) for t in after}
        snap["rows_written"] = {t: n for t, n in delta.items() if n}
        snap["rows_written_total"] = sum(n for n in delta.values() if n > 0)
    return snap


def job_is_running() -> bool:
    with _JOB_LOCK:
        return bool(_JOB["running"])


def job_start(run_id: str, triggered_by: str, steps: List[Dict[str, str]]) -> None:
    with _JOB_LOCK:
        _JOB.update({
            "running": True,
            "run_id": run_id,
            "started_at": datetime.now(timezone.utc).isoformat(),
            "finished_at": None,
            "triggered_by": triggered_by,
            "current_step": None,
            "status": "running",
            "steps": [{**s, "status": "pending", "started_at": None,
                       "finished_at": None, "detail": None, "rows": None,
                       "progress": None, "progress_at": None} for s in steps],
            "rows_before": {},
            "rows_after": {},
            "error": None,
        })


def job_step(key: str, status: str, detail: Optional[str] = None,
             rows: Optional[int] = None) -> None:
    """Mark a step's transition. ``status`` is running | ok | failed | skipped."""
    now = datetime.now(timezone.utc).isoformat()
    with _JOB_LOCK:
        for s in _JOB["steps"]:
            if s["key"] != key:
                continue
            s["status"] = status
            if status == "running":
                s["started_at"] = now
                _JOB["current_step"] = key
            else:
                s["finished_at"] = now
                s["progress"] = None
            if detail is not None:
                s["detail"] = str(detail)[:400]
            if rows is not None:
                s["rows"] = rows
            break


def job_step_progress(key: str, text: str) -> None:
    """Live sub-step text for a long step. The cost ETL spends tens of minutes inside
    a single step, so without this the UI cannot say which subscription or which cost
    grain it is on — which reads as 'stuck'."""
    with _JOB_LOCK:
        for s in _JOB["steps"]:
            if s["key"] == key:
                s["progress"] = str(text)[:200]
                s["progress_at"] = datetime.now(timezone.utc).isoformat()
                break


def job_finish(status: str, error: Optional[str] = None) -> None:
    with _JOB_LOCK:
        _JOB.update({
            "running": False,
            "finished_at": datetime.now(timezone.utc).isoformat(),
            "status": status,
            "current_step": None,
            "error": str(error)[:600] if error else None,
        })


def job_set_counts(when: str, counts: Dict[str, int]) -> None:
    """Record table row counts taken before/after the run (``when`` = before|after)."""
    with _JOB_LOCK:
        _JOB[f"rows_{when}"] = dict(counts)


# ── Census ───────────────────────────────────────────────────────────────────

def _fast_row_counts(cur) -> Dict[str, int]:
    """Row counts from Azure SQL metadata — no table scan, no locks.

    COUNT(*) across two dozen tables took ~13s, and while the ETL is writing it
    contends with those writes, which is why Refresh appeared dead mid-run.
    sys.dm_db_partition_stats answers from metadata in milliseconds.
    """
    if not is_azure_sql():
        return {}
    try:
        cur.execute(
            "SELECT t.name, SUM(p.row_count) "
            "FROM sys.dm_db_partition_stats p "
            "JOIN sys.tables t ON t.object_id = p.object_id "
            "WHERE p.index_id IN (0, 1) "
            "GROUP BY t.name"
        )
        return {str(r[0]): int(r[1] or 0) for r in cur.fetchall()}
    except Exception as exc:
        logger.debug("fast row count probe failed, falling back to COUNT(*): %s", exc)
        return {}


def table_counts() -> Dict[str, int]:
    """Row count for every catalogued table. Missing tables are simply absent."""
    counts: Dict[str, int] = {}
    try:
        with get_connection() as con:
            cur = con.cursor()
            fast = _fast_row_counts(cur)
            for meta in _av.DATASETS.values():
                t = meta["table"]
                if t not in _ALLOWED_TABLES:
                    continue
                if t in fast:
                    counts[t] = fast[t]
                    continue
                try:
                    cur.execute(f"SELECT COUNT(*) FROM {t}")
                    counts[t] = int(cur.fetchone()[0] or 0)
                except Exception:
                    continue
    except Exception as exc:
        logger.warning("table_counts failed: %s", exc)
    return counts


def _sub_column(cur, table: str) -> Optional[str]:
    """Which column on ``table`` names the subscription, if any."""
    try:
        cur.execute(
            "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = ?",
            (table,),
        )
        cols = {str(r[0]).lower() for r in cur.fetchall()}
    except Exception:
        # SQLite has no INFORMATION_SCHEMA — fall back to PRAGMA.
        try:
            cur.execute(f"PRAGMA table_info({table})")
            cols = {str(r[1]).lower() for r in cur.fetchall()}
        except Exception:
            return None
    for c in _SUB_COLUMNS:
        if c in cols:
            return c
    return None


def _subscription_breakdown(cur, table: str, col: str, limit: int = 25) -> List[Dict[str, Any]]:
    top = "TOP %d " % limit if is_azure_sql() else ""
    tail = "" if is_azure_sql() else f" LIMIT {limit}"
    try:
        cur.execute(
            f"SELECT {top}{col}, COUNT(*) FROM {table} GROUP BY {col} "
            f"ORDER BY COUNT(*) DESC{tail}"
        )
        return [{"subscription_id": str(r[0]) if r[0] else "(unattributed)",
                 "rows": int(r[1] or 0)} for r in cur.fetchall()]
    except Exception:
        return []


def _database_size() -> Optional[Dict[str, Any]]:
    if not is_azure_sql():
        return None
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT CAST(SUM(reserved_page_count) * 8.0 / 1024 AS DECIMAL(18,2)) "
                "FROM sys.dm_db_partition_stats"
            )
            used_mb = cur.fetchone()[0]
            return {"used_mb": float(used_mb) if used_mb is not None else None}
    except Exception as exc:
        logger.debug("database size probe failed: %s", exc)
        return None


def get_inventory(include_subscriptions: bool = True) -> Dict[str, Any]:
    """Full ingestion picture: every dataset, its rows, coverage window, freshness,
    and who it belongs to — plus the last ETL and any in-flight force run."""
    base = _av.get_availability(row_counts=table_counts())

    out: Dict[str, Any] = {
        "generated_at": base.get("generated_at"),
        "last_etl": base.get("last_etl"),
        "summary": base.get("summary"),
        "live_only_modules": base.get("live_only_modules"),
        "database": {"provider": "azure_sql" if is_azure_sql() else "sqlite"},
        "job": job_snapshot(),
        "datasets": [],
    }
    if base.get("error"):
        out["error"] = base["error"]

    size = _database_size()
    if size:
        out["database"].update(size)

    total_rows = 0
    sub_totals: Dict[str, int] = {}
    try:
        with get_connection() as con:
            cur = con.cursor()
            for key, entry in (base.get("datasets") or {}).items():
                fill = FILL_METHOD.get(key, _FILL_FALLBACK)
                row = {"key": key, **entry,
                       "fill_method": fill["method"], "how_to_fill": fill["how"]}
                total_rows += int(entry.get("rows") or 0)
                if include_subscriptions and entry.get("rows") and entry.get("status") == "ok":
                    tbl = entry.get("table")
                    if tbl in _ALLOWED_TABLES:
                        col = _sub_column(cur, tbl)
                        if col:
                            breakdown = _subscription_breakdown(cur, tbl, col)
                            row["by_subscription"] = breakdown
                            for s in breakdown:
                                sub_totals[s["subscription_id"]] = \
                                    sub_totals.get(s["subscription_id"], 0) + s["rows"]
                out["datasets"].append(row)
    except Exception as exc:
        logger.warning("inventory subscription breakdown failed: %s", exc)
        out["datasets"] = [{"key": k, **v,
                            "fill_method": FILL_METHOD.get(k, _FILL_FALLBACK)["method"],
                            "how_to_fill": FILL_METHOD.get(k, _FILL_FALLBACK)["how"]}
                           for k, v in (base.get("datasets") or {}).items()]
        total_rows = sum(int(v.get("rows") or 0) for v in (base.get("datasets") or {}).values())

    # Group ordering mirrors how the UI reads it: warehouse first, then scan, then input.
    order = {_av.SOURCE_WAREHOUSE: 0, _av.SOURCE_SCAN: 1, _av.SOURCE_USER: 2, _av.SOURCE_LIVE: 3}
    out["datasets"].sort(key=lambda d: (order.get(d.get("source"), 9), d.get("label", "")))
    out["total_rows"] = total_rows
    out["by_subscription"] = sorted(
        ({"subscription_id": k, "rows": v} for k, v in sub_totals.items()),
        key=lambda x: -x["rows"])

    # Only a "collection" dataset that is empty is an actual gap the button can close.
    out["actionable_gaps"] = [
        {"key": d["key"], "label": d["label"], "how_to_fill": d["how_to_fill"]}
        for d in out["datasets"]
        if d.get("fill_method") == "collection"
        and d.get("status") in ("empty", "collection_failed", "missing")
    ]
    return out
