"""
On-Premises PowerShell Script Builder — generates collection scripts
based on user-selected options with robust error handling.
"""
from __future__ import annotations

from typing import Dict, List


def generate_script(options: dict) -> str:
    """Generate a PowerShell collection script based on the provided options."""
    opt = _defaults(options)
    sections = [
        _header(opt),
        _parameters_block(opt),
        _helper_functions(),
        _server_resolution(opt),
        _output_setup(opt),
    ]

    # Add collection modules based on options
    if opt["collect_hardware"]:
        sections.append(_collect_hardware())
    if opt["collect_os"]:
        sections.append(_collect_os())
    if opt["collect_applications"]:
        sections.append(_collect_applications())
    if opt["collect_services"]:
        sections.append(_collect_services())
    if opt["collect_sql"]:
        sections.append(_collect_sql())
    if opt["collect_iis"]:
        sections.append(_collect_iis())
    if opt["collect_security"]:
        sections.append(_collect_security())
    if opt["collect_certificates"]:
        sections.append(_collect_certificates())
    if opt["collect_performance"]:
        sections.append(_collect_performance())

    sections.append(_main_loop(opt))
    sections.append(_export_and_compress(opt))
    sections.append(_footer())

    return "\n\n".join(sections)


def _defaults(options: dict) -> dict:
    defaults = {
        "collect_hardware": True,
        "collect_os": True,
        "collect_applications": True,
        "collect_services": True,
        "collect_sql": True,
        "collect_iis": True,
        "collect_security": True,
        "collect_certificates": True,
        "collect_performance": True,
        "collect_clustering": False,
        "collect_hyperv": False,
        "target_scope": "localhost",
        "custom_server_list": [],
        "domain_ou_filter": "",
        "credential_method": "current",
        "output_format": "csv",
        "compress_output": True,
        "max_concurrent": 5,
        "timeout_per_server": 300,
    }
    defaults.update(options)
    return defaults


# ═══════════════════════════════════════════════════════════════════════════════
# SCRIPT SECTIONS
# ═══════════════════════════════════════════════════════════════════════════════

def _header(opt: dict) -> str:
    return '''<#
.SYNOPSIS
    Azure Infrastructure Optimizer — On-Premises Server Data Collection Script
.DESCRIPTION
    Collects comprehensive server inventory data for migration assessment,
    BCDR planning, and hybrid cloud analysis. Generated by the Azure
    Infrastructure Optimization Platform.
.NOTES
    Script Version: 1.0.0
    Generated:      $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
    Requires:       PowerShell 5.1+ / PowerShell 7+
    Run As:         Administrator (recommended for full data collection)
#>

#Requires -Version 5.1
$ErrorActionPreference = "Continue"
$ProgressPreference    = "SilentlyContinue"
$ScriptVersion         = "1.0.0"
$CollectionTimestamp    = Get-Date -Format "yyyy-MM-dd_HHmmss"'''


def _parameters_block(opt: dict) -> str:
    server_list_default = ""
    if opt["target_scope"] == "custom_list" and opt["custom_server_list"]:
        escaped = '","'.join(opt["custom_server_list"])
        server_list_default = f'        [string[]]$ServerList = @("{escaped}"),'
    elif opt["target_scope"] == "localhost":
        server_list_default = '        [string[]]$ServerList = @($env:COMPUTERNAME),'
    else:
        server_list_default = '        [string[]]$ServerList = @(),'

    return f'''[CmdletBinding()]
param(
{server_list_default}
        [string]$OutputPath = ".\\OnPrem_Collection_$CollectionTimestamp",
        [int]$MaxConcurrent = {opt["max_concurrent"]},
        [int]$TimeoutSeconds = {opt["timeout_per_server"]},
        [switch]$SkipCompression
)'''


def _helper_functions() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

function Write-Status {
    param([string]$Message, [string]$Level = "INFO")
    $ts = Get-Date -Format "HH:mm:ss"
    $color = switch ($Level) {
        "ERROR"   { "Red" }
        "WARN"    { "Yellow" }
        "SUCCESS" { "Green" }
        default   { "Cyan" }
    }
    Write-Host "[$ts] [$Level] $Message" -ForegroundColor $color
}

function Invoke-SafeCommand {
    <#
    .SYNOPSIS
        Execute a script block with error handling; returns $null on failure.
    #>
    param(
        [ScriptBlock]$Command,
        [string]$Description = "command",
        [string]$Hostname = "localhost"
    )
    try {
        $result = & $Command
        return $result
    } catch {
        Write-Status "[$Hostname] Failed: $Description — $($_.Exception.Message)" -Level "WARN"
        return $null
    }
}

function Get-WmiSafe {
    <#
    .SYNOPSIS
        Try CIM first, fall back to WMI for older systems.
    #>
    param(
        [string]$ClassName,
        [string]$ComputerName = "localhost",
        [string]$Namespace = "root\cimv2"
    )
    try {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            return Get-CimInstance -ClassName $ClassName -Namespace $Namespace -ErrorAction Stop
        }
        return Get-CimInstance -ClassName $ClassName -Namespace $Namespace -ComputerName $ComputerName -ErrorAction Stop
    } catch {
        try {
            return Get-WmiObject -Class $ClassName -Namespace $Namespace -ComputerName $ComputerName -ErrorAction Stop
        } catch {
            Write-Status "[$ComputerName] CIM/WMI fallback failed for $ClassName — $($_.Exception.Message)" -Level "WARN"
            return $null
        }
    }
}'''


def _server_resolution(opt: dict) -> str:
    if opt["target_scope"] == "domain":
        ou_filter = ""
        if opt["domain_ou_filter"]:
            ou_filter = f' -SearchBase "{opt["domain_ou_filter"]}"'
        return f'''# ═══════════════════════════════════════════════════════════════════════════════
# SERVER RESOLUTION — Active Directory Discovery
# ═══════════════════════════════════════════════════════════════════════════════
if (-not $ServerList -or $ServerList.Count -eq 0) {{
    Write-Status "Discovering servers from Active Directory..."
    try {{
        Import-Module ActiveDirectory -ErrorAction Stop
        $adComputers = Get-ADComputer -Filter 'OperatingSystem -like "*Server*"'{ou_filter} -Properties OperatingSystem,LastLogonDate |
            Where-Object {{ $_.Enabled -eq $true -and $_.LastLogonDate -gt (Get-Date).AddDays(-90) }}
        $ServerList = $adComputers | Select-Object -ExpandProperty DNSHostName
        Write-Status "Found $($ServerList.Count) servers in AD" -Level "SUCCESS"
    }} catch {{
        Write-Status "AD discovery failed: $($_.Exception.Message). Falling back to localhost." -Level "ERROR"
        $ServerList = @($env:COMPUTERNAME)
    }}
}}'''
    else:
        return '''# ═══════════════════════════════════════════════════════════════════════════════
# SERVER RESOLUTION
# ═══════════════════════════════════════════════════════════════════════════════
if (-not $ServerList -or $ServerList.Count -eq 0) {
    $ServerList = @($env:COMPUTERNAME)
}
Write-Status "Target servers: $($ServerList -join ', ')"'''


def _output_setup(opt: dict) -> str:
    return '''# ═══════════════════════════════════════════════════════════════════════════════
# OUTPUT INITIALIZATION
# ═══════════════════════════════════════════════════════════════════════════════
New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
Write-Status "Output directory: $OutputPath"

# Result collections
$allServers     = [System.Collections.ArrayList]::new()
$allDisks       = [System.Collections.ArrayList]::new()
$allNetAdapters = [System.Collections.ArrayList]::new()
$allApps        = [System.Collections.ArrayList]::new()
$allServices    = [System.Collections.ArrayList]::new()
$allSqlInstances = [System.Collections.ArrayList]::new()
$allSqlDatabases = [System.Collections.ArrayList]::new()
$allIisSites    = [System.Collections.ArrayList]::new()
$allCerts       = [System.Collections.ArrayList]::new()'''


def _collect_hardware() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Hardware & System Info
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-HardwareInfo {
    param([string]$ComputerName)

    $cs = Get-WmiSafe -ClassName Win32_ComputerSystem -ComputerName $ComputerName
    $bios = Get-WmiSafe -ClassName Win32_BIOS -ComputerName $ComputerName
    $cpu = Get-WmiSafe -ClassName Win32_Processor -ComputerName $ComputerName | Select-Object -First 1

    $isVirtual = $false
    $hypervisor = ""
    if ($cs) {
        $mfg = ($cs.Manufacturer ?? "").ToLower()
        $mdl = ($cs.Model ?? "").ToLower()
        if ($mdl -match "virtual|vmware|kvm|xen|hyperv" -or $mfg -match "vmware|microsoft|xen|qemu") {
            $isVirtual = $true
            if ($mdl -match "vmware") { $hypervisor = "VMware" }
            elseif ($mdl -match "virtual" -or $mfg -match "microsoft") { $hypervisor = "Hyper-V" }
            elseif ($mdl -match "kvm" -or $mfg -match "qemu") { $hypervisor = "KVM" }
            else { $hypervisor = "Unknown" }
        }
    }

    return [PSCustomObject]@{
        Manufacturer       = $cs.Manufacturer ?? ""
        Model              = $cs.Model ?? ""
        SerialNumber       = $bios.SerialNumber ?? ""
        BIOSVersion        = $bios.SMBIOSBIOSVersion ?? ""
        TotalCores         = ($cpu.NumberOfCores ?? 0)
        LogicalProcessors  = ($cs.NumberOfLogicalProcessors ?? 0)
        TotalMemoryGB      = [math]::Round(($cs.TotalPhysicalMemory ?? 0) / 1GB, 1)
        CPUModel           = $cpu.Name ?? ""
        CPUSpeedGHz        = [math]::Round(($cpu.MaxClockSpeed ?? 0) / 1000, 2)
        IsVirtual          = $isVirtual
        HypervisorType     = $hypervisor
    }
}'''


def _collect_os() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Operating System
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-OSInfo {
    param([string]$ComputerName)

    $os = Get-WmiSafe -ClassName Win32_OperatingSystem -ComputerName $ComputerName

    $lastBoot = $null
    $uptimeDays = 0
    if ($os.LastBootUpTime) {
        try {
            $lastBoot = if ($os.LastBootUpTime -is [datetime]) { $os.LastBootUpTime }
                        else { [Management.ManagementDateTimeConverter]::ToDateTime($os.LastBootUpTime) }
            $uptimeDays = [math]::Round(((Get-Date) - $lastBoot).TotalDays, 0)
        } catch { $uptimeDays = 0 }
    }

    return [PSCustomObject]@{
        OSName          = $os.Caption ?? ""
        OSVersion       = $os.Version ?? ""
        OSBuild         = $os.BuildNumber ?? ""
        OSArchitecture  = $os.OSArchitecture ?? ""
        InstallDate     = try { $os.InstallDate.ToString("yyyy-MM-dd") } catch { "" }
        LastBootTime    = try { $lastBoot.ToString("yyyy-MM-dd HH:mm:ss") } catch { "" }
        UptimeDays      = $uptimeDays
    }
}'''


def _collect_applications() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Installed Applications
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-Applications {
    param([string]$ComputerName)

    $regPaths = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
    )
    $apps = @()
    if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
        foreach ($path in $regPaths) {
            $apps += Get-ItemProperty $path -ErrorAction SilentlyContinue |
                Where-Object { $_.DisplayName -and $_.DisplayName.Trim() -ne "" } |
                Select-Object @{N="Hostname";E={$ComputerName}},
                    @{N="Name";E={$_.DisplayName}},
                    @{N="Version";E={$_.DisplayVersion}},
                    @{N="Publisher";E={$_.Publisher}},
                    @{N="InstallDate";E={$_.InstallDate}}
        }
    } else {
        $apps = Invoke-Command -ComputerName $ComputerName -ErrorAction Stop -ScriptBlock {
            $paths = @(
                "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
                "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
            )
            $result = @()
            foreach ($p in $paths) {
                $result += Get-ItemProperty $p -ErrorAction SilentlyContinue |
                    Where-Object { $_.DisplayName -and $_.DisplayName.Trim() -ne "" } |
                    Select-Object @{N="Name";E={$_.DisplayName}},
                        @{N="Version";E={$_.DisplayVersion}},
                        @{N="Publisher";E={$_.Publisher}},
                        @{N="InstallDate";E={$_.InstallDate}}
            }
            $result
        } | Select-Object @{N="Hostname";E={$ComputerName}}, Name, Version, Publisher, InstallDate
    }
    return $apps
}'''


def _collect_services() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Windows Services
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-Services {
    param([string]$ComputerName)

    $services = Invoke-SafeCommand -Description "Services" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            Get-Service | Select-Object Name, DisplayName, Status, StartType
        } else {
            Get-Service -ComputerName $ComputerName | Select-Object Name, DisplayName, Status, StartType
        }
    }
    if (-not $services) { return @() }

    return $services | ForEach-Object {
        [PSCustomObject]@{
            Hostname    = $ComputerName
            Name        = $_.Name
            DisplayName = $_.DisplayName
            Status      = $_.Status.ToString()
            StartType   = $_.StartType.ToString()
            Account     = ""
        }
    }
}'''


def _collect_sql() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: SQL Server Discovery
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-SqlInstances {
    param([string]$ComputerName)

    $instances = @()
    $databases = @()

    # Discover SQL instances via registry
    $sqlServices = Invoke-SafeCommand -Description "SQL Services" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            Get-Service | Where-Object { $_.Name -match "^MSSQL\$|^MSSQLSERVER$" -and $_.Status -eq "Running" }
        } else {
            Get-Service -ComputerName $ComputerName | Where-Object { $_.Name -match "^MSSQL\$|^MSSQLSERVER$" -and $_.Status -eq "Running" }
        }
    }

    if (-not $sqlServices) { return @{ Instances = @(); Databases = @() } }

    foreach ($svc in $sqlServices) {
        $instName = if ($svc.Name -eq "MSSQLSERVER") { "MSSQLSERVER" } else { $svc.Name -replace "^MSSQL\$", "" }
        $connStr  = if ($instName -eq "MSSQLSERVER") { $ComputerName } else { "$ComputerName\$instName" }

        $sqlInfo = Invoke-SafeCommand -Description "SQL Info ($instName)" -Hostname $ComputerName -Command {
            $conn = New-Object System.Data.SqlClient.SqlConnection("Server=$connStr;Integrated Security=True;Connection Timeout=10")
            $conn.Open()
            $cmd = $conn.CreateCommand()
            $cmd.CommandText = "SELECT SERVERPROPERTY('ProductVersion') AS Version, SERVERPROPERTY('Edition') AS Edition, SERVERPROPERTY('ProductLevel') AS SP, SERVERPROPERTY('Collation') AS Collation"
            $reader = $cmd.ExecuteReader()
            $reader.Read() | Out-Null
            $info = [PSCustomObject]@{
                Version   = $reader["Version"]
                Edition   = $reader["Edition"]
                SP        = $reader["SP"]
                Collation = $reader["Collation"]
            }
            $reader.Close()

            # Get databases
            $cmd2 = $conn.CreateCommand()
            $cmd2.CommandText = @"
SELECT d.name, CAST(SUM(mf.size) * 8.0 / 1024 AS DECIMAL(18,1)) AS SizeMB,
       d.recovery_model_desc, d.compatibility_level, d.state_desc,
       (SELECT MAX(bs.backup_finish_date) FROM msdb.dbo.backupset bs WHERE bs.database_name = d.name) AS LastBackup
FROM sys.databases d
LEFT JOIN sys.master_files mf ON d.database_id = mf.database_id
WHERE d.database_id > 4
GROUP BY d.name, d.recovery_model_desc, d.compatibility_level, d.state_desc
"@
            $dbs = @()
            $reader2 = $cmd2.ExecuteReader()
            while ($reader2.Read()) {
                $dbs += [PSCustomObject]@{
                    DatabaseName  = $reader2["name"]
                    SizeMB        = [math]::Round($reader2["SizeMB"], 1)
                    RecoveryModel = $reader2["recovery_model_desc"]
                    CompatLevel   = $reader2["compatibility_level"]
                    State         = $reader2["state_desc"]
                    LastBackup    = if ($reader2["LastBackup"] -ne [DBNull]::Value) { $reader2["LastBackup"].ToString("yyyy-MM-dd HH:mm") } else { "" }
                }
            }
            $reader2.Close()
            $conn.Close()

            [PSCustomObject]@{ Info = $info; Databases = $dbs }
        }

        if ($sqlInfo) {
            $instances += [PSCustomObject]@{
                Hostname     = $ComputerName
                InstanceName = $instName
                Version      = $sqlInfo.Info.Version
                Edition      = $sqlInfo.Info.Edition
                ServicePack  = $sqlInfo.Info.SP
                Collation    = $sqlInfo.Info.Collation
                TCPPort      = 1433
                MaxMemoryMB  = 0
                MaxDOP       = 0
            }
            foreach ($db in $sqlInfo.Databases) {
                $databases += [PSCustomObject]@{
                    Hostname      = $ComputerName
                    InstanceName  = $instName
                    DatabaseName  = $db.DatabaseName
                    SizeMB        = $db.SizeMB
                    RecoveryModel = $db.RecoveryModel
                    CompatLevel   = $db.CompatLevel
                    State         = $db.State
                    LastBackup    = $db.LastBackup
                }
            }
        }
    }

    return @{ Instances = $instances; Databases = $databases }
}'''


def _collect_iis() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: IIS Web Sites
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-IISSites {
    param([string]$ComputerName)

    $sites = Invoke-SafeCommand -Description "IIS Sites" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            Import-Module WebAdministration -ErrorAction Stop
            Get-Website | Select-Object @{N="Hostname";E={$ComputerName}},
                @{N="SiteName";E={$_.Name}},
                @{N="Bindings";E={($_.Bindings.Collection | ForEach-Object { $_.bindingInformation }) -join "; "}},
                @{N="PhysicalPath";E={$_.PhysicalPath}},
                @{N="State";E={$_.State}},
                @{N="AppPool";E={$_.ApplicationPool}}
        } else {
            Invoke-Command -ComputerName $ComputerName -ScriptBlock {
                Import-Module WebAdministration -ErrorAction Stop
                Get-Website | Select-Object @{N="SiteName";E={$_.Name}},
                    @{N="Bindings";E={($_.Bindings.Collection | ForEach-Object { $_.bindingInformation }) -join "; "}},
                    @{N="PhysicalPath";E={$_.PhysicalPath}},
                    @{N="State";E={$_.State}},
                    @{N="AppPool";E={$_.ApplicationPool}}
            } | Select-Object @{N="Hostname";E={$ComputerName}}, SiteName, Bindings, PhysicalPath, State, AppPool
        }
    }
    return $sites ?? @()
}'''


def _collect_security() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Security Posture
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-SecurityInfo {
    param([string]$ComputerName)

    # Firewall
    $fw = Invoke-SafeCommand -Description "Firewall" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            Get-NetFirewallProfile -ErrorAction Stop | Select-Object Name, Enabled
        } else {
            Invoke-Command -ComputerName $ComputerName -ScriptBlock {
                Get-NetFirewallProfile | Select-Object Name, Enabled
            }
        }
    }
    $fwEnabled = ($fw | Where-Object { $_.Enabled }) -ne $null
    $fwProfiles = @{}
    if ($fw) { $fw | ForEach-Object { $fwProfiles[$_.Name] = [bool]$_.Enabled } }

    # Antivirus (Windows Defender or 3rd-party)
    $av = Invoke-SafeCommand -Description "Antivirus" -Hostname $ComputerName -Command {
        Get-WmiSafe -ClassName AntiVirusProduct -ComputerName $ComputerName -Namespace "root\SecurityCenter2"
    }
    $avProduct = ""
    $avStatus  = ""
    if ($av) {
        $avProduct = ($av | Select-Object -First 1).displayName ?? ""
        $avStatus  = "Installed"
    } else {
        # Check for Defender
        $defender = Invoke-SafeCommand -Description "Defender Status" -Hostname $ComputerName -Command {
            if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
                Get-MpComputerStatus -ErrorAction Stop
            }
        }
        if ($defender) {
            $avProduct = "Windows Defender"
            $avStatus  = if ($defender.RealTimeProtectionEnabled) { "Active" } else { "Disabled" }
        }
    }

    # Pending Windows Updates
    $pendingUpdates = Invoke-SafeCommand -Description "Pending Updates" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            $searcher = (New-Object -ComObject Microsoft.Update.Session).CreateUpdateSearcher()
            $results = $searcher.Search("IsInstalled=0 AND Type='Software'")
            $results.Updates.Count
        } else { 0 }
    }

    # Last Windows Update
    $lastUpdate = Invoke-SafeCommand -Description "Last Update" -Hostname $ComputerName -Command {
        $hotfix = Get-HotFix -ComputerName $ComputerName -ErrorAction Stop | Sort-Object InstalledOn -Descending | Select-Object -First 1
        if ($hotfix.InstalledOn) { $hotfix.InstalledOn.ToString("yyyy-MM-dd") } else { "" }
    }

    # Local Admins
    $localAdmins = Invoke-SafeCommand -Description "Local Admins" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            (Get-LocalGroupMember -Group "Administrators" -ErrorAction Stop).Name
        } else {
            Invoke-Command -ComputerName $ComputerName { (Get-LocalGroupMember -Group "Administrators").Name }
        }
    }

    return [PSCustomObject]@{
        FirewallEnabled    = $fwEnabled
        FirewallProfiles   = ($fwProfiles | ConvertTo-Json -Compress)
        AntivirusProduct   = $avProduct
        AntivirusStatus    = $avStatus
        PendingUpdates     = $pendingUpdates ?? 0
        LastUpdateDate     = $lastUpdate ?? ""
        LocalAdmins        = ($localAdmins -join ",") ?? ""
    }
}'''


def _collect_certificates() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Certificates
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-Certificates {
    param([string]$ComputerName)

    $certs = Invoke-SafeCommand -Description "Certificates" -Hostname $ComputerName -Command {
        if ($ComputerName -eq "localhost" -or $ComputerName -eq $env:COMPUTERNAME) {
            Get-ChildItem Cert:\LocalMachine\My -ErrorAction Stop | Select-Object Subject, Issuer, Thumbprint, NotAfter,
                @{N="Store";E={"LocalMachine\\My"}}
        } else {
            Invoke-Command -ComputerName $ComputerName -ScriptBlock {
                Get-ChildItem Cert:\LocalMachine\My | Select-Object Subject, Issuer, Thumbprint, NotAfter,
                    @{N="Store";E={"LocalMachine\\My"}}
            }
        }
    }
    if (-not $certs) { return @() }

    return $certs | ForEach-Object {
        [PSCustomObject]@{
            Hostname   = $ComputerName
            Subject    = $_.Subject
            Issuer     = $_.Issuer
            Thumbprint = $_.Thumbprint
            ExpiryDate = $_.NotAfter.ToString("yyyy-MM-dd")
            Store      = $_.Store
        }
    }
}'''


def _collect_performance() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# MODULE: Performance Baseline (5-sample quick snapshot)
# ═══════════════════════════════════════════════════════════════════════════════
function Collect-PerformanceBaseline {
    param([string]$ComputerName)

    $perf = Invoke-SafeCommand -Description "Performance Counters" -Hostname $ComputerName -Command {
        $samples = @()
        for ($i = 0; $i -lt 5; $i++) {
            $cpu = (Get-Counter '\Processor(_Total)\% Processor Time' -ComputerName $ComputerName -ErrorAction Stop).CounterSamples[0].CookedValue
            $mem = (Get-Counter '\Memory\% Committed Bytes In Use' -ComputerName $ComputerName -ErrorAction Stop).CounterSamples[0].CookedValue
            $samples += [PSCustomObject]@{ CPU = $cpu; Memory = $mem }
            if ($i -lt 4) { Start-Sleep -Seconds 2 }
        }
        [PSCustomObject]@{
            AvgCPU    = [math]::Round(($samples.CPU | Measure-Object -Average).Average, 1)
            AvgMemory = [math]::Round(($samples.Memory | Measure-Object -Average).Average, 1)
            PeakCPU   = [math]::Round(($samples.CPU | Measure-Object -Maximum).Maximum, 1)
            PeakMemory = [math]::Round(($samples.Memory | Measure-Object -Maximum).Maximum, 1)
        }
    }
    return $perf
}'''


def _main_loop(opt: dict) -> str:
    credential_block = ""
    if opt["credential_method"] == "prompt":
        credential_block = '''
# Prompt for credentials
$Credential = Get-Credential -Message "Enter credentials for remote server access"
'''

    modules_to_collect = []
    if opt["collect_hardware"]:
        modules_to_collect.append("Hardware")
    if opt["collect_os"]:
        modules_to_collect.append("OS")
    if opt["collect_applications"]:
        modules_to_collect.append("Applications")
    if opt["collect_services"]:
        modules_to_collect.append("Services")
    if opt["collect_sql"]:
        modules_to_collect.append("SQL")
    if opt["collect_iis"]:
        modules_to_collect.append("IIS")
    if opt["collect_security"]:
        modules_to_collect.append("Security")
    if opt["collect_certificates"]:
        modules_to_collect.append("Certificates")
    if opt["collect_performance"]:
        modules_to_collect.append("Performance")

    return f'''{credential_block}
# ═══════════════════════════════════════════════════════════════════════════════
# MAIN COLLECTION LOOP
# ═══════════════════════════════════════════════════════════════════════════════
$totalServers = $ServerList.Count
$current = 0
$collectionStart = Get-Date
$failedServers = @()

Write-Status "Starting collection for $totalServers server(s)..." -Level "INFO"
Write-Status "Modules: {', '.join(modules_to_collect)}"

foreach ($server in $ServerList) {{
    $current++
    $pctComplete = [math]::Round(($current / $totalServers) * 100)
    Write-Progress -Activity "Collecting Server Data" -Status "$server ($current/$totalServers)" -PercentComplete $pctComplete

    Write-Status "[$current/$totalServers] Collecting from $server..."
    $serverStart = Get-Date

    # Test connectivity first
    $reachable = Test-Connection -ComputerName $server -Count 1 -Quiet -ErrorAction SilentlyContinue
    if (-not $reachable -and $server -ne $env:COMPUTERNAME -and $server -ne "localhost") {{
        Write-Status "[$server] UNREACHABLE — skipping" -Level "ERROR"
        $failedServers += $server
        continue
    }}

    # Build server record
    $serverRecord = [PSCustomObject]@{{
        Hostname = $server
        FQDN = try {{ [System.Net.Dns]::GetHostEntry($server).HostName }} catch {{ $server }}
        Domain = try {{ (Get-WmiSafe -ClassName Win32_ComputerSystem -ComputerName $server).Domain }} catch {{ "" }}
        CollectedAt = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
    }}
''' + _build_module_calls(opt) + r'''
    # Calculate duration
    $duration = (Get-Date) - $serverStart
    $serverRecord | Add-Member -NotePropertyName "CollectionDurationSec" -NotePropertyValue ([math]::Round($duration.TotalSeconds, 1))

    [void]$allServers.Add($serverRecord)
    Write-Status "[$server] Complete in $([math]::Round($duration.TotalSeconds, 1))s" -Level "SUCCESS"
}

Write-Progress -Activity "Collecting Server Data" -Completed'''


def _build_module_calls(opt: dict) -> str:
    calls = []

    if opt["collect_hardware"]:
        calls.append(r'''
    # Hardware
    $hw = Invoke-SafeCommand -Description "Hardware" -Hostname $server -Command { Collect-HardwareInfo -ComputerName $server }
    if ($hw) {
        $serverRecord | Add-Member -NotePropertyName "Manufacturer" -NotePropertyValue $hw.Manufacturer
        $serverRecord | Add-Member -NotePropertyName "Model" -NotePropertyValue $hw.Model
        $serverRecord | Add-Member -NotePropertyName "SerialNumber" -NotePropertyValue $hw.SerialNumber
        $serverRecord | Add-Member -NotePropertyName "BIOSVersion" -NotePropertyValue $hw.BIOSVersion
        $serverRecord | Add-Member -NotePropertyName "TotalCores" -NotePropertyValue $hw.TotalCores
        $serverRecord | Add-Member -NotePropertyName "LogicalProcessors" -NotePropertyValue $hw.LogicalProcessors
        $serverRecord | Add-Member -NotePropertyName "TotalMemoryGB" -NotePropertyValue $hw.TotalMemoryGB
        $serverRecord | Add-Member -NotePropertyName "CPUModel" -NotePropertyValue $hw.CPUModel
        $serverRecord | Add-Member -NotePropertyName "CPUSpeedGHz" -NotePropertyValue $hw.CPUSpeedGHz
        $serverRecord | Add-Member -NotePropertyName "IsVirtual" -NotePropertyValue $hw.IsVirtual
        $serverRecord | Add-Member -NotePropertyName "HypervisorType" -NotePropertyValue $hw.HypervisorType
    }''')

    if opt["collect_os"]:
        calls.append(r'''
    # Operating System
    $osInfo = Invoke-SafeCommand -Description "OS Info" -Hostname $server -Command { Collect-OSInfo -ComputerName $server }
    if ($osInfo) {
        $serverRecord | Add-Member -NotePropertyName "OSName" -NotePropertyValue $osInfo.OSName
        $serverRecord | Add-Member -NotePropertyName "OSVersion" -NotePropertyValue $osInfo.OSVersion
        $serverRecord | Add-Member -NotePropertyName "OSBuild" -NotePropertyValue $osInfo.OSBuild
        $serverRecord | Add-Member -NotePropertyName "OSArchitecture" -NotePropertyValue $osInfo.OSArchitecture
        $serverRecord | Add-Member -NotePropertyName "InstallDate" -NotePropertyValue $osInfo.InstallDate
        $serverRecord | Add-Member -NotePropertyName "LastBootTime" -NotePropertyValue $osInfo.LastBootTime
        $serverRecord | Add-Member -NotePropertyName "UptimeDays" -NotePropertyValue $osInfo.UptimeDays
    }''')

    if opt["collect_applications"]:
        calls.append(r'''
    # Applications
    $apps = Invoke-SafeCommand -Description "Applications" -Hostname $server -Command { Collect-Applications -ComputerName $server }
    if ($apps) { $apps | ForEach-Object { [void]$allApps.Add($_) } }''')

    if opt["collect_services"]:
        calls.append(r'''
    # Services
    $svcs = Invoke-SafeCommand -Description "Services" -Hostname $server -Command { Collect-Services -ComputerName $server }
    if ($svcs) { $svcs | ForEach-Object { [void]$allServices.Add($_) } }''')

    if opt["collect_sql"]:
        calls.append(r'''
    # SQL Server
    $sqlData = Invoke-SafeCommand -Description "SQL Discovery" -Hostname $server -Command { Collect-SqlInstances -ComputerName $server }
    if ($sqlData) {
        $sqlData.Instances | ForEach-Object { [void]$allSqlInstances.Add($_) }
        $sqlData.Databases | ForEach-Object { [void]$allSqlDatabases.Add($_) }
    }''')

    if opt["collect_iis"]:
        calls.append(r'''
    # IIS Sites
    $iisSites = Invoke-SafeCommand -Description "IIS" -Hostname $server -Command { Collect-IISSites -ComputerName $server }
    if ($iisSites) { $iisSites | ForEach-Object { [void]$allIisSites.Add($_) } }''')

    if opt["collect_security"]:
        calls.append(r'''
    # Security
    $sec = Invoke-SafeCommand -Description "Security" -Hostname $server -Command { Collect-SecurityInfo -ComputerName $server }
    if ($sec) {
        $serverRecord | Add-Member -NotePropertyName "FirewallEnabled" -NotePropertyValue $sec.FirewallEnabled
        $serverRecord | Add-Member -NotePropertyName "AntivirusProduct" -NotePropertyValue $sec.AntivirusProduct
        $serverRecord | Add-Member -NotePropertyName "AntivirusStatus" -NotePropertyValue $sec.AntivirusStatus
        $serverRecord | Add-Member -NotePropertyName "PendingUpdates" -NotePropertyValue $sec.PendingUpdates
        $serverRecord | Add-Member -NotePropertyName "LastUpdateDate" -NotePropertyValue $sec.LastUpdateDate
    }''')

    if opt["collect_certificates"]:
        calls.append(r'''
    # Certificates
    $certs = Invoke-SafeCommand -Description "Certificates" -Hostname $server -Command { Collect-Certificates -ComputerName $server }
    if ($certs) { $certs | ForEach-Object { [void]$allCerts.Add($_) } }''')

    if opt["collect_performance"]:
        calls.append(r'''
    # Performance Baseline
    $perf = Invoke-SafeCommand -Description "Performance" -Hostname $server -Command { Collect-PerformanceBaseline -ComputerName $server }
    if ($perf) {
        $serverRecord | Add-Member -NotePropertyName "AvgCPU" -NotePropertyValue $perf.AvgCPU
        $serverRecord | Add-Member -NotePropertyName "AvgMemory" -NotePropertyValue $perf.AvgMemory
        $serverRecord | Add-Member -NotePropertyName "PeakCPU" -NotePropertyValue $perf.PeakCPU
        $serverRecord | Add-Member -NotePropertyName "PeakMemory" -NotePropertyValue $perf.PeakMemory
    }''')

    # Disk collection (always included with hardware)
    calls.append(r'''
    # Disks
    $disks = Invoke-SafeCommand -Description "Disk Info" -Hostname $server -Command {
        $volumes = Get-WmiSafe -ClassName Win32_LogicalDisk -ComputerName $server | Where-Object { $_.DriveType -eq 3 }
        $totalStorage = 0; $totalFree = 0
        $diskResults = @()
        foreach ($vol in $volumes) {
            $sizeGB = [math]::Round($vol.Size / 1GB, 1)
            $freeGB = [math]::Round($vol.FreeSpace / 1GB, 1)
            $usedPct = if ($sizeGB -gt 0) { [math]::Round((1 - $freeGB / $sizeGB) * 100, 1) } else { 0 }
            $totalStorage += $sizeGB; $totalFree += $freeGB
            $diskResults += [PSCustomObject]@{
                Hostname   = $server
                DriveLetter = $vol.DeviceID
                Label      = $vol.VolumeName ?? ""
                SizeGB     = $sizeGB
                FreeGB     = $freeGB
                UsedPct    = $usedPct
                FileSystem = $vol.FileSystemName ?? $vol.FileSystem ?? ""
            }
        }
        [PSCustomObject]@{ Disks = $diskResults; TotalStorageGB = $totalStorage; TotalFreeGB = $totalFree }
    }
    if ($disks) {
        $serverRecord | Add-Member -NotePropertyName "TotalStorageGB" -NotePropertyValue $disks.TotalStorageGB
        $serverRecord | Add-Member -NotePropertyName "TotalFreeGB" -NotePropertyValue $disks.TotalFreeGB
        $disks.Disks | ForEach-Object { [void]$allDisks.Add($_) }
    }

    # Network Adapters
    $adapters = Invoke-SafeCommand -Description "Network" -Hostname $server -Command {
        if ($server -eq "localhost" -or $server -eq $env:COMPUTERNAME) {
            Get-NetAdapter -Physical -ErrorAction SilentlyContinue | ForEach-Object {
                $config = Get-NetIPConfiguration -InterfaceIndex $_.ifIndex -ErrorAction SilentlyContinue
                [PSCustomObject]@{
                    Hostname       = $server
                    AdapterName    = $_.Name
                    IPAddress      = ($config.IPv4Address.IPAddress -join ",")
                    SubnetMask     = ($config.IPv4Address.PrefixLength -join ",")
                    DefaultGateway = ($config.IPv4DefaultGateway.NextHop -join ",")
                    DNSServers     = (($config.DNSServer | Where-Object AddressFamily -eq 2).ServerAddresses -join ",")
                    SpeedMbps      = [math]::Round($_.LinkSpeed -replace "[^0-9.]","")
                    MACAddress     = $_.MacAddress
                    Status         = $_.Status
                }
            }
        } else {
            Get-WmiSafe -ClassName Win32_NetworkAdapterConfiguration -ComputerName $server |
                Where-Object { $_.IPEnabled } | ForEach-Object {
                [PSCustomObject]@{
                    Hostname       = $server
                    AdapterName    = $_.Description
                    IPAddress      = ($_.IPAddress -join ",")
                    SubnetMask     = ($_.IPSubnet -join ",")
                    DefaultGateway = ($_.DefaultIPGateway -join ",")
                    DNSServers     = ($_.DNSServerSearchOrder -join ",")
                    SpeedMbps      = 0
                    MACAddress     = $_.MACAddress
                    Status         = "Up"
                }
            }
        }
    }
    if ($adapters) { $adapters | ForEach-Object { [void]$allNetAdapters.Add($_) } }

    # Server Roles & IP Addresses
    $serverRecord | Add-Member -NotePropertyName "IPAddresses" -NotePropertyValue (($adapters | ForEach-Object { $_.IPAddress }) -join ",")
    $roles = Invoke-SafeCommand -Description "Server Roles" -Hostname $server -Command {
        if ($server -eq "localhost" -or $server -eq $env:COMPUTERNAME) {
            (Get-WindowsFeature | Where-Object { $_.Installed -and $_.FeatureType -eq "Role" }).Name -join ","
        } else {
            (Invoke-Command -ComputerName $server { (Get-WindowsFeature | Where-Object { $_.Installed -and $_.FeatureType -eq "Role" }).Name }) -join ","
        }
    }
    $serverRecord | Add-Member -NotePropertyName "ServerRoles" -NotePropertyValue ($roles ?? "")''')

    return "\n".join(calls)


def _export_and_compress(opt: dict) -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# EXPORT RESULTS
# ═══════════════════════════════════════════════════════════════════════════════
$collectionEnd = Get-Date
$totalDuration = $collectionEnd - $collectionStart

Write-Status "Exporting results..."

# Server Inventory (main CSV)
if ($allServers.Count -gt 0) {
    $allServers | Export-Csv -Path "$OutputPath\Server_Inventory.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  Server_Inventory.csv — $($allServers.Count) servers"
}
if ($allDisks.Count -gt 0) {
    $allDisks | Export-Csv -Path "$OutputPath\Disk_Storage.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  Disk_Storage.csv — $($allDisks.Count) records"
}
if ($allNetAdapters.Count -gt 0) {
    $allNetAdapters | Export-Csv -Path "$OutputPath\Network_Adapters.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  Network_Adapters.csv — $($allNetAdapters.Count) records"
}
if ($allApps.Count -gt 0) {
    $allApps | Export-Csv -Path "$OutputPath\Applications.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  Applications.csv — $($allApps.Count) records"
}
if ($allServices.Count -gt 0) {
    $allServices | Export-Csv -Path "$OutputPath\Services.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  Services.csv — $($allServices.Count) records"
}
if ($allSqlInstances.Count -gt 0) {
    $allSqlInstances | Export-Csv -Path "$OutputPath\SQL_Instances.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  SQL_Instances.csv — $($allSqlInstances.Count) records"
}
if ($allSqlDatabases.Count -gt 0) {
    $allSqlDatabases | Export-Csv -Path "$OutputPath\SQL_Databases.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  SQL_Databases.csv — $($allSqlDatabases.Count) records"
}
if ($allIisSites.Count -gt 0) {
    $allIisSites | Export-Csv -Path "$OutputPath\IIS_Sites.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  IIS_Sites.csv — $($allIisSites.Count) records"
}
if ($allCerts.Count -gt 0) {
    $allCerts | Export-Csv -Path "$OutputPath\Certificates.csv" -NoTypeInformation -Encoding UTF8
    Write-Status "  Certificates.csv — $($allCerts.Count) records"
}

# Write manifest
$manifest = @{
    script_version    = $ScriptVersion
    collection_date   = $CollectionTimestamp
    total_servers     = $allServers.Count
    failed_servers    = $failedServers
    duration_seconds  = [math]::Round($totalDuration.TotalSeconds, 1)
    modules_collected = @(''' + str([m for m in ["Server_Inventory", "Disk_Storage", "Network_Adapters", "Applications", "Services", "SQL_Instances", "SQL_Databases", "IIS_Sites", "Certificates"]]) + r''')
} | ConvertTo-Json -Depth 3
$manifest | Out-File -FilePath "$OutputPath\collection_manifest.json" -Encoding UTF8

# ── Compress ──────────────────────────────────────────────────────────────────
if (-not $SkipCompression) {
    $zipPath = "$OutputPath.zip"
    Write-Status "Compressing to $zipPath..."
    try {
        Compress-Archive -Path "$OutputPath\*" -DestinationPath $zipPath -Force
        Write-Status "ZIP created: $zipPath" -Level "SUCCESS"
    } catch {
        Write-Status "Compression failed: $($_.Exception.Message)" -Level "WARN"
    }
}'''


def _footer() -> str:
    return r'''# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════
Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║         COLLECTION COMPLETE                               ║" -ForegroundColor Green
Write-Host "╠════════════════════════════════════════════════════════════╣" -ForegroundColor Green
Write-Host "║  Servers Collected : $($allServers.Count.ToString().PadLeft(5))                                 ║" -ForegroundColor White
Write-Host "║  Servers Failed    : $($failedServers.Count.ToString().PadLeft(5))                                 ║" -ForegroundColor $(if ($failedServers.Count -gt 0) { "Yellow" } else { "White" })
Write-Host "║  Total Duration    : $([math]::Round($totalDuration.TotalMinutes, 1).ToString().PadLeft(5)) min                             ║" -ForegroundColor White
Write-Host "║  Output Path       : $OutputPath                          ║" -ForegroundColor White
Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "Upload the generated ZIP file to the Azure Infrastructure" -ForegroundColor Cyan
Write-Host "Optimizer platform for analysis and migration planning." -ForegroundColor Cyan
Write-Host ""'''
